/**
*  Decrypter.hpp
*  Decrypter Class header file.
*  Runs the decryption algorithm to a message by using the key generated by the Encrypter Class.
*  Uses Encrypter.hpp
*
*
*  Created by Salil D. Maharjan on 10/10/19.
*  Copyright © 2019 Salil Maharjan. All rights reserved.
*/

#pragma once
#include "PrefixHeader.pch"

class Decrypter{
private:
    /**
    * Variable to hold the key used for decryption purposes. User input.
    */
    string m_key;
    
    /**
    * Variable to hold the message to decrypt.
    */
    string m_encrypted;
    
    /**
    * Method to read encrypted message and key to decrypt the message.
    */
    void readMessageKey(string a_fileName);
    
    /**
    *  Method to decrypt by custom 5-Block Feistel style cipher.
    */
    string fiveBlockFeistel(string a_encrypted);
    
    /**
    * Method to decrypt using Caesar's cipher.
    */
    string caesarDecrypter(string a_encrypted);
    
    /**
    * Method to use the p-box to get original string.
    */
    string revPBoxPermutation(string a_encrypted);
    
    /**
    * Method to use the s-box to get original string.
    */
    string revSBoxSubstitution(string a_encrypted);
    
    /**
    * Method to decrypt using vigenere cipher.
    */
    string vigenereDecrypter(string a_encrypted, int b_key, int e_key);
    
    

    
public:
    // *********************************************************
    // ************** Default Constructor **********************
    // *********************************************************
    Decrypter();
    // *********************************************************
    // ************** Default Destructor ***********************
    // *********************************************************
    ~Decrypter();
    
    /**
    * Method to Decrypt file.
    */
    void DecryptMessage();
    
};
